version: '3.9'
services:
  server:
    build:
      dockerfile: Dockerfile
    container_name: server
    ports:
      - '8080:8080'
    depends_on:
      db:
        condition: service_started
  db:
    restart: always
    image: postgres:latest
    container_name: library
    environment:
      - POSTGRES_PASSWORD=library
      - POSTGRES_DB=library
    ports:
      - '5432:5432'
    volumes:
      - ./table.sql:/docker-entrypoint-initdb.d/table.sql